[theme]
# Primary accent for interactive elements
primaryColor = "#1f77b4"
# Background color for the main content area
backgroundColor = "#D8D87B"
# Background color for sidebar and expanded menu
secondaryBackgroundColor = "#D8D87B"
