[theme]
# Primary accent for interactive elements
primaryColor = "#f8c215"
# Background color for the main content area
backgroundColor = "#272723"
# Background color for sidebar and expanded menu
secondaryBackgroundColor = "#f8c215"
textColor="#FFFFFF"
