[theme]
# Primary accent for interactive elements
primaryColor = "#F5F3EC"
# Background color for the main content area
backgroundColor = "#272723"
# Background color for sidebar and expanded menu
secondaryBackgroundColor = "#F3D98F"
textColor="#FFFFFF"
